codecov:
  notify:
    after_n_builds: 1
  ignore:
    - "**/CAContract_StrategyBase.cs"
    - "**/CAContract_StrategyHelper.cs"
    - "**/CAContract_StrategyImpl.cs"
    - "**/CAContract_SyncCAHolder.cs"