codecov:
  notify:
    after_n_builds: 1
  ignore:
    - "contract/Portkey.Contracts.CA/CAContract_StrategyBase.cs"
    - "contract/Portkey.Contracts.CA/CAContract_StrategyHelper.cs"
    - "contract/Portkey.Contracts.CA/CAContract_StrategyImpl.cs"
    - "contract/Portkey.Contracts.CA/CAContract_SyncCAHolder.cs"